-- DRGUI Phase 3B.2 Testing Script
-- Copy and paste these commands one by one in WoW chat to test Smart Profile Manager

print("=== DRGUI Phase 3B.2 Testing Script ===")
print("Copy these commands one by one:")
print("")
print("1. Basic Status Check:")
print("/drgui status")
print("")
print("2. Hero Talent Detection:")
print("/drgui hero-talents")
print("")
print("3. Profile Manager Availability:")
print("/script print('ProfileManager Available:', DRGUI.ActionBars.ProfileManager ~= nil)")
print("")
print("4. Test Profile Creation:")
print("/drgui create-hero-profile TestFatebound")
print("")
print("5. List All Profiles:")
print("/drgui profiles")
print("")
print("6. Debug Smart Profile Manager:")
print("/script if DRGUI.ActionBars.ProfileManager then print('✅ ProfileManager loaded') DRGUI.ActionBars.ProfileManager:Initialize() else print('❌ ProfileManager not loaded') end")
print("")
print("Expected Results:")
print("- Status should show hero talent info")
print("- Hero-talents should show 'Fatebound' for ID 52")
print("- ProfileManager should be available")
print("- Profile creation should work without errors")
print("- Profiles list should show created profiles")